# Generated by Django 4.1.3 on 2024-05-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("swapi_handler", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DownloadedDataset",
            new_name="DatasetMetadata",
        ),
        migrations.CreateModel(
            name="DatasetFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="csv_files/")),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="swapi_handler.datasetmetadata",
                    ),
                ),
            ],
        ),
    ]
